/**
* Generated file

* Generated from: yang module name: btil-provider-impl  yang module local name: btil-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Feb 05 11:05:32 CET 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sitb_btil_provider.impl;

import com.bt.sitb.opendaylight.controller.sample.btil.provider.OpendaylightBtil;
import org.opendaylight.controller.md.sal.binding.api.DataBroker;
import org.opendaylight.controller.md.sal.binding.api.DataChangeListener;
import org.opendaylight.controller.md.sal.common.api.data.AsyncDataBroker.DataChangeScope;
import org.opendaylight.controller.md.sal.common.api.data.LogicalDatastoreType;
import org.opendaylight.controller.sal.binding.api.BindingAwareBroker;
import org.opendaylight.yang.gen.v1.https.office.bt.com.sites.sitb.btil.rev141018.SitbBtilService;
import org.opendaylight.yangtools.concepts.ListenerRegistration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
*
*/
public final class SitbBtilProviderModule extends
        org.opendaylight.controller.config.yang.config.sitb_btil_provider.impl.AbstractSitbBtilProviderModule {
    private static final Logger log = LoggerFactory.getLogger(SitbBtilProviderModule.class);

    public SitbBtilProviderModule(final org.opendaylight.controller.config.api.ModuleIdentifier identifier,
                                     final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        super(identifier, dependencyResolver);
        log.info ("*************** SitbBtilProviderModule constructor") ;

    }

    public SitbBtilProviderModule(final org.opendaylight.controller.config.api.ModuleIdentifier identifier,
                                     final org.opendaylight.controller.config.api.DependencyResolver dependencyResolver,
                                     final SitbBtilProviderModule oldModule, final AutoCloseable oldInstance) {

        super(identifier, dependencyResolver, oldModule, oldInstance);
        log.info ("*************** SitbBtilProviderModule constructor") ;
    }


    @Override
    protected void customValidation() {
        // No need to validate dependencies, since all dependencies have
        // mandatory true flag in yang
        // config-subsystem will perform the validation for dependencies
    }

    @Override
    public AutoCloseable createInstance() {
        log.info ("*************** Create Instance of SitB Btil") ;
        final OpendaylightBtil opendaylightBtil = new OpendaylightBtil();

        // Register to md-sal
        opendaylightBtil.setNotificationProvider(getNotificationServiceDependency());

        DataBroker dataBrokerService = getDataBrokerDependency();
        opendaylightBtil.setDataProvider(dataBrokerService);

        final ListenerRegistration<DataChangeListener> dataChangeListenerRegistration = dataBrokerService
                .registerDataChangeListener(LogicalDatastoreType.CONFIGURATION, OpendaylightBtil.TOASTER_IID,
                        opendaylightBtil, DataChangeScope.SUBTREE);

        final BindingAwareBroker.RpcRegistration<SitbBtilService> rpcRegistration = getRpcRegistryDependency()
                .addRpcImplementation(SitbBtilService.class, opendaylightBtil);

        // Register runtimeBean for btil statistics via JMX
        final SitbBtilProviderRuntimeRegistration runtimeReg = getRootRuntimeBeanRegistratorWrapper().register(
                opendaylightBtil);

        // Wrap btil as AutoCloseable and close registrations to md-sal at
        // close()
        final class AutoCloseableBtil implements AutoCloseable {

            @Override
            public void close() throws Exception {
                dataChangeListenerRegistration.close();
                rpcRegistration.close();
                runtimeReg.close();
                closeQuietly(opendaylightBtil);
                log.info("Btil provider (instance {}) torn down.", this);
            }

            private void closeQuietly(final AutoCloseable resource) {
                try {
                    resource.close();
                } catch (final Exception e) {
                    log.debug("Ignoring exception while closing {}", resource, e);
                }
            }
        }

        AutoCloseable ret = new AutoCloseableBtil();
        log.info("Btil provider (instance {}) initialized.", ret);
        return ret;
    }
}
