/**
* Generated file

* Generated from: yang module name: btil-provider-impl  yang module local name: btil-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Feb 05 11:05:32 CET 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.sitb_btil_provider.impl;

/**
*
*/
public class SitbBtilProviderModuleFactory extends org.opendaylight.controller.config.yang.config.sitb_btil_provider.impl.AbstractSitbBtilProviderModuleFactory
{


}
